### PR TITLE
Fix tsconfig so build works

### PR DESCRIPTION
**Pull request by mortenmoulder**

### CODE REVIEW

**Comment by HugoJF** [comment]
When using `npm run dev` do you have any problems building the project? I just tested with a fresh clone and everything seems to work fine.

**Comment by mortenmoulder** [comment]
@HugoJF I have not tested, because the installation steps doesn't tell me to install `cross-env`. I don't understand the need for `lavavel-mix` either.

My steps works completely without the need of webpack. Just run `tsc` (which everyone should have installed, and if not, I've added the steps in the README) and it will look at tsconfig, which then builds to a build folder.

**Comment by HugoJF** [comment]
As I said, the README is not up-to-date.

The reason I use Laravel Mix is because I'm just used to it. I might consider replacing it in the future, but for now, I don't see any need to change.

 EDIT: can `tsc` auto-build on changes? That's probably the biggest reason I'm using Laravel Mix

**Comment by mortenmoulder** [comment]
@HugoJF Using the default TypeScript compiler is in my opinion a lot better. No need for 3rd party libraries etc.

Yes, you can with the `-w` or `--watch` flag. I would recommend changing the package.json to something like:

```
  "scripts": {
    "start": "node build/index.js",
    "lint": "eslint src/**",
    "dev": "npm run watch",
    "prod": "npm run build",
    "build": "tsc",
    "watch": "tsc --watch",
  },
```

If you want to run dev environment, it will compile the TypeScript and watch for new changes. If you want to run prod environment, it just builds with `tsc` and doesn't watch.

Then all the user needs, is to `npm install -g typescript`. Or maybe you can install it in node_modules and run it that way, but I'm not sure what's best practise there.

**Comment by HugoJF** [comment]
I'm going to keep Laravel Mix for now because I really don't want to mess with this right now. But I'll keep this PR open because I agree with removing Laravel Mix and WebPack in favor of only having `tsc`

EDIT: what about source maps?

**Comment by mortenmoulder** [comment]
@HugoJF What about them? Should be supported out of the box with the default TypeScript compiler.

Waiting happily for the VOD download feature. This can definitely wait :)

**Comment by czingenberg** [comment]
+1 for VOD download

**Comment by HugoJF** [comment]
> @HugoJF What about them? Should be supported out of the box with the default TypeScript compiler.
> 
> Waiting happily for the VOD download feature. This can definitely wait :)



> +1 for VOD download


VOD downloads are mostly implemented in the master branch. I'm still ironing a few problems out but should be usable. I decided to merge it before finishing everything after realizing how unusable it was at that state. Once everything seems stable, I'll move development to a development branch.

Let me know if you encounter any problems.

**Comment by mortenmoulder** [comment]
@HugoJF Video downloads seem to be working for me. The file structure is a bit meh, and I think cleaning up the .ts files in the folders before going to the next video is a better priority.

But yeah, works great for me. Good job 👍

**Comment by HugoJF** [comment]
Finally ditched laravel-mix in 45c025f55eba2cef47815e0f9cf422c78b6e3152. Thank you!

**Pull request closed without merging**
